package square.api.domain.errors;

import com.fasterxml.jackson.annotation.JsonCreator;

public enum ErrorCode {

  USERNAME_VALIDATION_ERROR,
  USERNAME_LENGTH_MISMATCH,
  USERNAME_NULL_OR_EMPTY,

  TOKEN_LENGTH_MISMATCH,
  TOKEN_NULL_OR_EMPTY,
  TOKEN_TIME_NULL,
  TOKEN_MISMATCH,
  TOKEN_EXPIRED,

  PASSWORD_VALIDATION_ERROR,
  PASSWORD_LENGTH_MISMATCH,
  PASSWORD_NULL_OR_EMPTY,
  PASSWORD_MISMATCH,

  USER_FIRST_NAME_LENGTH_MISMATCH,
  USER_FIRST_NAME_NULL_OR_EMPTY_OR_BLANK_SPACE,
  USER_LAST_NAME_TOO_LONG,
  USER_LAST_NAME_NULL,
  USER_ALREADY_ACTIVATED,
  USER_NOT_ACTIVATED,
  USER_ALREADY_EXISTS,
  USER_NOT_FOUND,
  USER_DELETED,

  ROLE_TYPE_NOT_VALID,
  ROLE_TYPE_NULL,

  EMAIL_VALIDATION_ERROR,
  EMAIL_LENGTH_MISMATCH,
  EMAIL_ALREADY_EXISTS,
  EMAIL_NULL_OR_EMPTY,

  VALIDATION_ERROR_REQUEST_PARAM,

  NUMBER_ID_LENGTH_MISMATCH,

  NUMBER_LENGTH_MISMATCH,
  NUMBER_NOT_FOUND,
  NUMBER_NULL;

  @JsonCreator
  public static ErrorCode forValue(String value) {
    return ErrorCode.valueOf(value);
  }
}
